//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/maftMac/MaftPacket.msg.
//

#ifndef _MAFTPACKET_M_H_
#define _MAFTPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "MacPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/mac/maftMac/MaftPacket.msg:5</tt> by nedtool.
 * <pre>
 * packet MaftPacket extends MacPacket
 * {
 *     int ptype;
 * 
 *     int pair_count;
 *     int txer[5];
 *     int rxer[5];
 *     int channel[5];
 * 
 *     int x;
 *     int y;
 *     int v;
 * 
 *     double time_val;
 *     double del_t;
 * }
 * </pre>
 */
class MaftPacket : public ::MacPacket
{
  protected:
    int ptype_var;
    int pair_count_var;
    int txer_var[5];
    int rxer_var[5];
    int channel_var[5];
    int x_var;
    int y_var;
    int v_var;
    double time_val_var;
    double del_t_var;

  private:
    void copy(const MaftPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MaftPacket&);

  public:
    MaftPacket(const char *name=NULL, int kind=0);
    MaftPacket(const MaftPacket& other);
    virtual ~MaftPacket();
    MaftPacket& operator=(const MaftPacket& other);
    virtual MaftPacket *dup() const {return new MaftPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPtype() const;
    virtual void setPtype(int ptype);
    virtual int getPair_count() const;
    virtual void setPair_count(int pair_count);
    virtual unsigned int getTxerArraySize() const;
    virtual int getTxer(unsigned int k) const;
    virtual void setTxer(unsigned int k, int txer);
    virtual unsigned int getRxerArraySize() const;
    virtual int getRxer(unsigned int k) const;
    virtual void setRxer(unsigned int k, int rxer);
    virtual unsigned int getChannelArraySize() const;
    virtual int getChannel(unsigned int k) const;
    virtual void setChannel(unsigned int k, int channel);
    virtual int getX() const;
    virtual void setX(int x);
    virtual int getY() const;
    virtual void setY(int y);
    virtual int getV() const;
    virtual void setV(int v);
    virtual double getTime_val() const;
    virtual void setTime_val(double time_val);
    virtual double getDel_t() const;
    virtual void setDel_t(double del_t);
};

inline void doPacking(cCommBuffer *b, MaftPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MaftPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MAFTPACKET_M_H_

