//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/PacketId.msg.
//

#ifndef _PACKETID_M_H_
#define _PACKETID_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/routing/PacketId.msg:7</tt> by nedtool.
 * <pre>
 * packet PacketId extends RoutingPacket
 * {
 *     unsigned int id;
 * }
 * </pre>
 */
class PacketId : public ::RoutingPacket
{
  protected:
    unsigned int id_var;

  private:
    void copy(const PacketId& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketId&);

  public:
    PacketId(const char *name=NULL, int kind=0);
    PacketId(const PacketId& other);
    virtual ~PacketId();
    PacketId& operator=(const PacketId& other);
    virtual PacketId *dup() const {return new PacketId(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getId() const;
    virtual void setId(unsigned int id);
};

inline void doPacking(cCommBuffer *b, PacketId& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PacketId& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PACKETID_M_H_

