//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/ourProt/CPacket.msg.
//

#ifndef _CPACKET_M_H_
#define _CPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "MacPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/mac/ourProt/CPacket.msg:5</tt> by nedtool.
 * <pre>
 * packet CPacket extends MacPacket
 * {
 *     int ptype; // 3 = REPLY Packet
 *     int adst; // actual destination
 *     int fdst = 5; //final destination
 *     int sourceX;
 *     int sourceY;
 *     int destX;
 *     int destY;
 *     int myX;
 *     int myY;
 * 
 *     int slots;
 *     int slot_info[10];
 *     int node_id[10];
 * 
 *     double time_val;
 *     double del_t;
 * }
 * </pre>
 */
class CPacket : public ::MacPacket
{
  protected:
    int ptype_var;
    int adst_var;
    int fdst_var;
    int sourceX_var;
    int sourceY_var;
    int destX_var;
    int destY_var;
    int myX_var;
    int myY_var;
    int slots_var;
    int slot_info_var[10];
    int node_id_var[10];
    double time_val_var;
    double del_t_var;

  private:
    void copy(const CPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CPacket&);

  public:
    CPacket(const char *name=NULL, int kind=0);
    CPacket(const CPacket& other);
    virtual ~CPacket();
    CPacket& operator=(const CPacket& other);
    virtual CPacket *dup() const {return new CPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPtype() const;
    virtual void setPtype(int ptype);
    virtual int getAdst() const;
    virtual void setAdst(int adst);
    virtual int getFdst() const;
    virtual void setFdst(int fdst);
    virtual int getSourceX() const;
    virtual void setSourceX(int sourceX);
    virtual int getSourceY() const;
    virtual void setSourceY(int sourceY);
    virtual int getDestX() const;
    virtual void setDestX(int destX);
    virtual int getDestY() const;
    virtual void setDestY(int destY);
    virtual int getMyX() const;
    virtual void setMyX(int myX);
    virtual int getMyY() const;
    virtual void setMyY(int myY);
    virtual int getSlots() const;
    virtual void setSlots(int slots);
    virtual unsigned int getSlot_infoArraySize() const;
    virtual int getSlot_info(unsigned int k) const;
    virtual void setSlot_info(unsigned int k, int slot_info);
    virtual unsigned int getNode_idArraySize() const;
    virtual int getNode_id(unsigned int k) const;
    virtual void setNode_id(unsigned int k, int node_id);
    virtual double getTime_val() const;
    virtual void setTime_val(double time_val);
    virtual double getDel_t() const;
    virtual void setDel_t(double del_t);
};

inline void doPacking(cCommBuffer *b, CPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CPACKET_M_H_

