//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/leachRouting/LeachRoutingPacket.msg.
//

#ifndef _LEACHROUTINGPACKET_M_H_
#define _LEACHROUTINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/routing/leachRouting/LeachRoutingPacket.msg:26</tt> by nedtool.
 * <pre>
 * enum LeachRoutingPacket_Type
 * {
 * 
 *     LEACH_ROUTING_ADV_PACKET = 1;
 *     LEACH_ROUTING_JOIN_PACKET = 2;
 *     LEACH_ROUTING_TDMA_PACKET = 3;
 *     LEACH_ROUTING_DATA_PACKET = 4;
 * }
 * </pre>
 */
enum LeachRoutingPacket_Type {
    LEACH_ROUTING_ADV_PACKET = 1,
    LEACH_ROUTING_JOIN_PACKET = 2,
    LEACH_ROUTING_TDMA_PACKET = 3,
    LEACH_ROUTING_DATA_PACKET = 4
};

/**
 * Class generated from <tt>src/node/communication/routing/leachRouting/LeachRoutingPacket.msg:34</tt> by nedtool.
 * <pre>
 * packet LeachRoutingPacket extends RoutingPacket
 * {
 *     int LeachRoutingPacketKind @enum(LeachRoutingPacket_Type);
 *     int schedule[];
 * }
 * </pre>
 */
class LeachRoutingPacket : public ::RoutingPacket
{
  protected:
    int LeachRoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;

  private:
    void copy(const LeachRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LeachRoutingPacket&);

  public:
    LeachRoutingPacket(const char *name=NULL, int kind=0);
    LeachRoutingPacket(const LeachRoutingPacket& other);
    virtual ~LeachRoutingPacket();
    LeachRoutingPacket& operator=(const LeachRoutingPacket& other);
    virtual LeachRoutingPacket *dup() const {return new LeachRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getLeachRoutingPacketKind() const;
    virtual void setLeachRoutingPacketKind(int LeachRoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
};

inline void doPacking(cCommBuffer *b, LeachRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LeachRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _LEACHROUTINGPACKET_M_H_

